xjdr/xio

compile, src/main/java/com/xjeffrose/xio/EPollSelectorImpl.java, src/main/java/com/xjeffrose/xio/Future.java, src/main/java/com/xjeffrose/xio/FutureTask.java, xio
This will allow us to Modify the Selector, Future and FutureTask for performance tuning in the future.
=> Fix the EPoll selector and the FutureTask to be much better

dev.sh, src/main/groovy/RestServiceExample.groovy, src/main/java/com/xjeffrose/xio/Acceptor.java, src/main/java/com/xjeffrose/xio/ClientChannelContext.java, src/main/java/com/xjeffrose/xio/EventLoop.java, src/main/java/com/xjeffrose/xio/HttpObject.java, src/main/java/com/xjeffrose/xio/HttpParser.java, src/main/java/com/xjeffrose/xio/HttpRequest.java, src/main/java/com/xjeffrose/xio/HttpResponse.java, src/main/java/com/xjeffrose/xio/HttpResponseParser.java, src/main/java/com/xjeffrose/xio/PooService.java, src/main/java/com/xjeffrose/xio/Route.java, src/main/java/com/xjeffrose/xio/Server.java, src/main/java/com/xjeffrose/xio/ServerChannelContext.java, src/main/java/com/xjeffrose/xio/Service.java, src/test/groovy/com/xjeffrose/xio/HttpParser.groovy, src/test/groovy/com/xjeffrose/xio/HttpResponseParser.groovy, src/test/groovy/com/xjeffrose/xio/HttpServer.groovy, src/test/groovy/com/xjeffrose/xio/Route.groovy, test
We did make awesome, shall we land it?
=> Opendev 2015 02 20

src/main/java/com/xjeffrose/xio/processor/XioProcessor.java, src/main/java/com/xjeffrose/xio/server/XioDispatcher.java, src/test/java/com/xjeffrose/xio/fixtures/XioTestProcessor.java, src/test/java/com/xjeffrose/xio/server/XioServerFunctionalTest.java
Move Dispatcher to ChannelInboundHandlerAdapter and add disconnect to processor interface.
=> Move Dispatcher to ChannelInboundHandlerAdapter and add disconnect to

src/main/java/com/xjeffrose/xio/server/Route.java
=> changing Route class to Public

src/main/java/com/xjeffrose/xio/client/HttpClientConnector.java
Also fixes the confusion caused by milli vs sec
=> Remove redundant HttpClient DisconnectHandler

.circleci.settings.xml, circle.yml, pom.xml
https://circleci.com/blog/optimizing-maven-builds-on-circleci/
=> setup packagecloud

TODO.org, src/main/java/com/xjeffrose/xio/http/DefaultFullRequest.java, src/main/java/com/xjeffrose/xio/http/DefaultStreamingRequest.java, src/main/java/com/xjeffrose/xio/http/EmptyHeaders.java, src/main/java/com/xjeffrose/xio/http/Http2ClientCodec.java, src/main/java/com/xjeffrose/xio/http/Http2FrameForwarder.java, src/main/java/com/xjeffrose/xio/http/Http2Handler.java, src/main/java/com/xjeffrose/xio/http/Http2Request.java, src/main/java/com/xjeffrose/xio/http/Http2Response.java, src/main/java/com/xjeffrose/xio/http/Http2ServerCodec.java, src/main/java/com/xjeffrose/xio/http/Request.java, src/main/java/com/xjeffrose/xio/http/Response.java, src/main/java/com/xjeffrose/xio/http/StreamingRequestData.java, src/main/java/com/xjeffrose/xio/http/internal/FullHttp2Request.java, src/main/java/com/xjeffrose/xio/http/internal/FullHttp2Response.java, src/main/java/com/xjeffrose/xio/http/internal/Http1Headers.java, src/main/java/com/xjeffrose/xio/http/internal/Http1Request.java, src/main/java/com/xjeffrose/xio/http/internal/Http1Response.java, src/main/java/com/xjeffrose/xio/http/internal/Http2HeadersWrapper.java, src/main/java/com/xjeffrose/xio/http/internal/Http2StreamingData.java, src/main/java/com/xjeffrose/xio/http/internal/StreamingHttp2Request.java, src/main/java/com/xjeffrose/xio/http/internal/StreamingHttp2Response.java, src/test/java/com/xjeffrose/xio/http/GrpcFunctionalTest.java, src/test/java/com/xjeffrose/xio/http/Http2ClientCodecUnitTest.java, src/test/java/com/xjeffrose/xio/http/Http2ServerCodecUnitTest.java, src/test/java/com/xjeffrose/xio/http/internal/Http2HeadersWrapperUnitTest.java
=> Wrap Http2 objects

xio-core/pom.xml
=> adding alpn-boot dependencies for new jdk

circle.yml
=> disable packagecloud in circleci config

xio-core/src/main/java/com/xjeffrose/xio/http/DefaultFullResponse.java, xio-core/src/main/java/com/xjeffrose/xio/http/DefaultSegmentedResponse.java, xio-core/src/main/java/com/xjeffrose/xio/http/ProxyBackendHandler.java
propagating streamid for proxied requests
=> TACO-131 - propagation of streamid for proxied requests

xio-core/src/main/java/com/xjeffrose/xio/http/Http2ClientCodec.java, xio-core/src/main/java/com/xjeffrose/xio/http/Http2ClientHandler.java, xio-core/src/main/java/com/xjeffrose/xio/http/Http2ServerHandler.java, xio-core/src/test/java/com/xjeffrose/xio/http/ReverseProxyFunctionalTest.java
and adding adding additional h1 to h2 proxy tests
=> TACO-162 fixing h2 to h2 interleaved and segmented

.circleci/config.yml, alpn-boot.gradle, gradle.properties
determining alpn-boot version based on jdk version
=> determine alpn-boot version

int-test-backend-server/src/main/java/com/xjeffrose/xio/backend/server/Main.java, int-tests/test_server.py, int-tests/unsafe_client.py
turnin' over rocks - finding bugs - proxy post integration tests
=> TACO-231 proxy post integration tests

int-tests/test_server.py, xio-core/src/main/java/com/xjeffrose/xio/http/ClientPool.java, xio-core/src/test/java/com/xjeffrose/xio/http/ClientPoolTest.java
temporarily disabling the client pool and getting all the integration tests to pass
=> TACO-231 disable client pool temporarily

int-tests/server_controller.py
cleanly killing server processes in pyunit integration tests
=> TACO-300 clean kills

build.gradle
removing native classifier - again
=> remove classifier

.circleci/config.yml, int-test-backend-server/Dockerfile, int-test-proxy-server/Dockerfile, int-test-proxy-server/docker-app.conf, int-tests/Dockerfile, int-tests/README.md, int-tests/docker-compose.yml, int-tests/proxy_load_tests.py
* pyunit h2load test
* adding `Dockerfile`s for the int-test services and pyunit test client
* adding docker-compose for running  load test
=> TACO-309 containerize an h2load test

docker-images/testing-python3-wrk-h2load/Dockerfile, int-test-backend-server/Dockerfile, int-test-proxy-server/Dockerfile, int-tests/Dockerfile, int-tests/README.md, int-tests/container_tests.sh, int-tests/docker-compose.yml, int-tests/proxy_load_tests.py, int-tests/requirements.txt
* adding h1 load test with wrk
* docker-compose up runs integration tests without interaction
note: h1 tests fail since we are asserting 0 errors out of 100s of thousands ... acceptable error rates TBD
=> TACO-329 h1 load test with wrk

int-test-proxy-server/src/main/java/com/xjeffrose/xio/proxy/Main.java, int-test-proxy-server/src/main/java/com/xjeffrose/xio/proxy/ReverseProxyServer.java, int-test-proxy-server/src/main/java/com/xjeffrose/xio/proxy/RouteStates.java, int-test-proxy-server/src/test/java/com/xjeffrose/xio/proxy/ReverseProxyFunctionalTest.java, int-test-proxy-server/src/test/resources/application.conf, xio-core/src/main/java/com/xjeffrose/xio/http/ClientFactory.java, xio-core/src/main/java/com/xjeffrose/xio/http/ProxyClientFactory.java, xio-core/src/test/java/com/xjeffrose/xio/config/DynamicRouteConfigsFactoryUnitTest.java
fixing proxy when a single client connection attempts to reach multiple, desperate backends
=> proxy bugfix - multiple backends - single client connection

int-test-proxy-server/src/test/java/com/xjeffrose/xio/proxy/ReverseProxyFunctionalTest.java, xio-core/src/main/java/com/xjeffrose/xio/http/ProxyHandler.java
responding with a 503 rather than closing connection to client when failing to write to a proxied backend
=> proxy error response rather than conn close
